globals:
  working-directory: .
  simulator-arguments:
    sampling-frequency: 2048
    duration: 128
    max-samples: 50
  output-directory: output
  metadata-directory: metadata
simulators:
  noise:
    class: PyCBCStationaryGaussianNoiseSimulator
    arguments:
      detectors:
        - ET1
      label: EinsteinTelescopeP1600143
      seed: 0
    output:
      file_name: "{{ detectors }}-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: STRAIN
