globals:
  simulator-arguments:
    sampling-frequency: 4096
    duration: 1024
    start-time: 1577491218
    total-duration: "5 hours"
  working-directory: .
  output-directory: output
  metadata-directory: metadata

simulators:
  noise:
    class: ColoredNoiseSimulator
    arguments:
      psd_file: ET_10_full_cryo_psd.txt
      seed: 42
      detectors: ["E1"]
    output:
      file_name: "{{ detectors }}-NOISE_STRAIN-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: "{{ detectors }}-STRAIN"
