globals:
  simulator-arguments:
    sampling-frequency: 4096
    duration: 4096
    total-duration: "1 day"
    start-time: 1577491218
  working-directory: "./ET_Triangle_Sardinia_noise"
  output-directory: "data"
  metadata-directory: "metadata"

simulators:
  noise:
    class: ColoredNoiseSimulator
    arguments:
      psd_file: ET_10_full_cryo_psd.txt
      detectors:
        - E1_Triangle_Sardinia
        - E2_Triangle_Sardinia
        - E3_Triangle_Sardinia
      low_frequency_cutoff: 2
      seed: 42
    output:
      file_name: "E-{{ detectors }}_NOISE_STRAIN-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: "{{ detectors }}:STRAIN"
